[build-system]
requires = ["setuptools>=82.0.0", "pybind11>=3.0.2"]
build-backend = "setuptools.build_meta"

[project]
name = "tmalign"
version = "0.1.0"
description = "TM-align protein structure comparison"
requires-python = ">=3.12"
dependencies = [
    "gemmi>=0.7.4",
    "numpy>=2.4.2",
]
